#
# Copyright (C) 2019 - All Rights Reserved
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.
#

logging:
    path: /var/log/spring-boot/sv-spring-boot-admin
    file: ${logging.path}/${LOGFILE:sv-spring-boot-admin.log}
    level:
        root: info
        de:
            codecentric: info
        org.springframework.security: trace # allows ldap debugging
        com.softvision.sv.spring.boot.admin.config: info


server:
   port: ${PORT:8988}


spring:
    application:
        name: @project.artifactId@
    # controls the login credentials to the main admin page
    security:
        user:
            name: admin
            password: admin

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: ALWAYS



